# Generated by Django 4.1.7 on 2023-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('arrival_date_is_flexible', models.BooleanField(null=True)),
                ('departure_date_is_flexible', models.BooleanField(null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
