# Generated by Django 4.1.7 on 2023-04-17 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='anc_country',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='anc_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.city'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='volunteer_hosts',
            field=models.ManyToManyField(blank=True, related_name='hosts_anc', to=settings.AUTH_USER_MODEL),
        ),
    ]
