# Generated by Django 4.1.7 on 2023-04-10 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='volunteer_hosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='hosts_anc', to=settings.AUTH_USER_MODEL),
        ),
    ]
