# Generated by Django 4.1.7 on 2023-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_announcement_announcer_alter_announcement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="travelers_count",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                ],
                null=True,
            ),
        ),
    ]
