# Generated by Django 4.1.7 on 2023-04-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_main_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='arrival_date_is_flexible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='departure_date_is_flexible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
