# Generated by Django 4.1.7 on 2023-04-04 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_remove_announcement_anc_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='volunteer_hosts',
            field=models.ManyToManyField(related_name='hosts_anc', to=settings.AUTH_USER_MODEL),
        ),
    ]
