# Generated by Django 4.1.7 on 2023-03-28 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0003_announcement_travelers_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='city',
            new_name='anc_city',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='country',
            new_name='anc_country',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='timestamp_created',
            new_name='anc_timestamp_created',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='anc_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='anc_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Done'), ('E', 'Expired')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='announcement',
            name='main_host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_host_anc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='volunteer_hosts',
            field=models.ManyToManyField(related_name='hosts_anc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='announcer_anc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='arrival_date_is_flexible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='departure_date_is_flexible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
