# Generated by Django 4.1.7 on 2023-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_volunteer_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='volunteer_hosts',
        ),
    ]
