# Generated by Django 4.1.7 on 2023-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_remove_announcement_volunteer_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='anc_country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='anc_city',
            field=models.CharField(max_length=100),
        ),
    ]
