# Generated by Django 4.1.7 on 2023-03-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_user_city'),
        ('announcement', '0004_rename_city_announcement_anc_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='anc_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.city'),
        ),
    ]
