# Generated by Django 4.1.7 on 2023-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcement_anc_country_alter_announcement_anc_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='anc_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='anc_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
