# Generated by Django 4.1.7 on 2023-05-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
        ('feedback', '0004_alter_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ans_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ans', to='announcement.announcement'),
            preserve_default=False,
        ),
    ]
