# Generated by Django 4.1.7 on 2023-05-17 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_blog_feedback_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('liked_post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('liker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
