# Generated by Django 4.1.7 on 2023-05-23 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_feedback_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liked_post', 'liker')},
        ),
    ]
