# Generated by Django 4.1.7 on 2023-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maximum_number_of_guests',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_gender_to_host',
            field=models.CharField(blank=True, choices=[(1, 'Any'), (2, 'Male'), (3, 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sleeping_arrangments',
            field=models.CharField(blank=True, choices=[(1, 'shared_bed'), (2, 'shared_room'), (3, 'private_room'), (4, 'public_room')], max_length=20, null=True),
        ),
    ]
