# Generated by Django 4.1.7 on 2023-04-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, default=None, to='utils.userinterest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='langF',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langF', to='utils.language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='langL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langL', to='utils.language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
