# Generated by Django 4.1.7 on 2023-04-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='interest_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
