# Generated by Django 4.1.7 on 2023-03-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'country')},
        ),
    ]
