# Generated by Django 4.1.7 on 2023-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=1, null=True),
        ),
    ]
