# Generated by Django 4.1.7 on 2023-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('accounts', '0002_alter_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, default=None, to='utils.userinterest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='langF',
            field=models.ManyToManyField(blank=True, default=None, related_name='langF', to='utils.language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='langL',
            field=models.ManyToManyField(blank=True, default=None, related_name='langL', to='utils.language'),
        ),
    ]
