# Generated by Django 4.1.7 on 2023-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_language_userinterest_user_amazing_thing_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='accounts.userinterest'),
        ),
    ]
