# Generated by Django 4.1.7 on 2023-05-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_image_code_alter_user_profile_photo'),
        ('accounts', '0002_user_maximum_number_of_guests_and_more'),
    ]

    operations = [
    ]
