# Generated by Django 4.1.7 on 2023-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='announcements_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
