# Generated by Django 4.1.7 on 2023-05-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20230508_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_to_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
