# Generated by Django 4.1.7 on 2023-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_coin_to_buy_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin_to_buy',
            field=models.IntegerField(default=5),
        ),
    ]
