# Generated by Django 4.1.7 on 2023-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='old_username', max_length=255),
            preserve_default=False,
        ),
    ]
