# Generated by Django 4.1.7 on 2023-04-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_nationality_user_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='s',
            new_name='User_nationality',
        ),
    ]
