# Generated by Django 4.1.7 on 2023-04-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_announcements_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='announcements_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
    ]
