# Generated by Django 4.1.7 on 2023-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_about_me_user_education_user_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<built-in function id>', max_length=255),
        ),
    ]
