# Generated by Django 4.1.7 on 2023-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_again",
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
