# Generated by Django 4.1.7 on 2023-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_image_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('c_lat', models.FloatField()),
                ('c_long', models.FloatField()),
                ('abbrev_city', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='about_me',
            new_name='User_about_me',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='User_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='User_birthdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='User_city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='User_country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country_code',
            new_name='User_country_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='education',
            new_name='User_education',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='job',
            new_name='User_job',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nationality',
            new_name='User_nationality',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='User_phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postal_code',
            new_name='User_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='User_address_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='User_address_long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='User_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
