# Generated by Django 4.1.7 on 2023-03-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_city_rename_about_me_user_user_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
