# Generated by Django 4.1.7 on 2023-03-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_city',
        ),
    ]
