# Generated by Django 4.1.7 on 2023-03-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
