# Generated by Django 4.1.7 on 2023-04-19 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_title', models.CharField(blank=True, max_length=500)),
                ('blog_text', models.TextField(blank=True)),
                ('json_data', models.JSONField(blank=True, default=dict, null=True)),
                ('main_image_64', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=250, null=True)),
                ('annoncement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='TaggedModel', to='blog.tag')),
            ],
        ),
    ]
