# Generated by Django 4.1.7 on 2023-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, null=True),
        ),
    ]
