# Generated by Django 4.1.7 on 2023-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='main_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='main_image_64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
