# Generated by Django 4.1.7 on 2023-05-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feedback_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedback'),
        ),
    ]
