# Generated by Django 4.1.7 on 2023-04-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_main_image_blog_main_image_64'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='json_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
