# Generated by Django 4.1.7 on 2023-04-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_volunteer_hosts'),
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='annoncement',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
            preserve_default=False,
        ),
    ]
