# Generated by Django 4.1.7 on 2023-04-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_volunteer_hosts'),
        ('blog', '0003_blog_annoncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='annoncement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
    ]
