# Generated by Django 4.1.7 on 2023-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_city_city_image64'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='explore_more',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.TextField(blank=True, null=True),
        ),
    ]
