# Generated by Django 4.1.7 on 2023-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_city_area_city_currency_city_explore_more_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_image64',
            new_name='city_big_image64',
        ),
        migrations.AddField(
            model_name='city',
            name='city_small_image64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
