# Generated by Django 4.1.7 on 2023-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_rename_city_image64_city_city_big_image64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_big_image64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_small_image64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
