# Generated by Django 4.1.7 on 2023-05-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_message_ans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('sent', 'sent'), ('received', 'received')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
