# Generated by Django 4.1.7 on 2023-07-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ans_id',
        ),
    ]
